# Generated by Django 4.2.16 on 2024-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_booked_price',
            field=models.FloatField(default=0.0),
        ),
    ]
