# Generated by Django 4.2.16 on 2024-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbail',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
    ]
