# Generated by Django 4.2.16 on 2024-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_price_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='short_clip',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa')], default='esewa', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
