# Generated by Django 4.2.16 on 2024-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
